steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg=VERSION=$TAG_NAME', '--tag=eu.gcr.io/$PROJECT_ID/rclone:$TAG_NAME', '.']
images: ['eu.gcr.io/$PROJECT_ID/rclone:$TAG_NAME']
